### ISSUE TITLE
TODO Frontend

### ISSUE THREAD

**Issue by FreddyKly** [FreddyKly/Rat-Detector#14]
- [ ] Show list of confidences
- [ ] show Date correctly
- [ ] only load 50 latest images
- [ ] check if "Hot-Reload" for new Images is possible
- [ ] remove unused routes
